version: '3'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    # volumes:
    #   - <chemin_local_config>:/config
    #   - <chemin_local_media>:/tv
    #   - <chemin_local_download>:/downloads